const theme = {
  light: {
    theme: 'light',
    color: 'black',
    subcolor: 'grey',
    background: 'white',
    borderColor: 'transparent',
    toggleTrack: 'black',
    toggleThumb: '#d4d4d4',
    logout: 'white',
    logoutBorder: 'red',
    mailboxcolor: '#E9E9E9',
    navPink: '#FF8F8F',
    navGreen: '#779874',
    navcolor: 'black',
    shuffle:'rgba(0,0,0,0.1)',
    modalbackground: 'rgba(0,0,0,0.5)',
  },
  dark: {
    theme: 'dark',
    color: 'white',
    subcolor: '#d4d4d4',
    background: 'black',
    borderColor: '#d4d4d4',
    toggleTrack: 'white',
    toggleThumb: '#b1b1b1',
    logout: '#C61010',
    mailboxcolor: '#b1b1b1',
    navPink: '#FF8F8F',
    navGreen: '#779874',
    navcolor: '#d4d4d4',
    shuffle:'rgba(225,225,225,0.3)',
    modalbackground: 'rgba(225,225,225,0.5)',
    modalButton: 'transparent'
  },
};
export default theme;
